version: '2'

services:
  dotnetcore_postgresql:
    image: dotnetcore_postgresql:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
